name: unit-tests

on:
  workflow_call:

jobs:
  black:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.5
          architecture: "x64"
      - name: install tox
        run: |
          pip install tox
      - name: black
        run: tox -e unit-tests
