name: Сборка проекта

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v3
      - name: Настройка NodeJS
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          cache: "pnpm"

      - name: Авторизация в GitHub Packages
        run: echo >> .npmrc "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}"

      - name: Установка зависимостей
        run: pnpm install --prod --ignore-scripts

      - name: Сборка проекта
        run: pnpm build
