name: Линт

on:
  workflow_call:

jobs:
  eslint:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    env:
      PUPPETEER_SKIP_DOWNLOAD: true
    steps:
      - uses: actions/checkout@v4
      - name: Настройка NodeJS
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"

      - name: Авторизация в GitHub Packages
        run: echo >> .npmrc "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}"

      - name: Установка зависимостей
        run: pnpm install

      - name: ESLint
        run: pnpm lint

  prettier:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    env:
      PUPPETEER_SKIP_DOWNLOAD: true
    steps:
      - uses: actions/checkout@v4
      - name: Настройка NodeJS
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"

      - name: Авторизация в GitHub Packages
        run: echo >> .npmrc "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}"

      - name: Установка зависимостей
        run: pnpm install

      - name: Prettier
        run: pnpm prettier
