name: Обновление версии в package.json

on:
  workflow_call:
    inputs:
      version:
        description: "Версия для package.json"
        required: true
        type: string
    secrets:
      GPG_PRIVATE_KEY:
        required: true
        description: "Ключ для подписи коммита"

jobs:
  update-package-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Настройка NodeJS
        uses: actions/setup-node@v3

      - name: Конфигурация пользователя
        run: |
          git config --global user.email "y.cloud@mypacific.ru"
          git config --global user.name "pacific-bot"

      - name: Импорт ключа GPG
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Обновление версии
        run: |
          npm config set sign-git-tag true
          npm version ${{ inputs.version }} -m "release: Релиз \`v${{ inputs.version }}\`"
          git push --follow-tags
